/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.lab4_javaswing;
import java.awt.Image;
import javax.swing.*;
import java.awt.Dimension;

/**
 *
 * @author Admin
 */
public class detailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form detailsPanel
     */
    private User newUser;
    
    public detailsPanel(User newUser) {
        initComponents();
        this.newUser = newUser;
        populateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameValidationLabel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        UploadPhoto = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageText = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        maleSelect = new javax.swing.JRadioButton();
        femaleSelect = new javax.swing.JRadioButton();
        otherSelect = new javax.swing.JRadioButton();
        Message1 = new javax.swing.JLabel();
        ageText = new javax.swing.JSpinner();
        howDidYouKnowAboutUs = new javax.swing.JLabel();
        typeSelect = new javax.swing.JComboBox<>();
        previewImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateText = new com.toedter.calendar.JDateChooser();
        date = new javax.swing.JLabel();

        firstNameValidationLabel.setBackground(new java.awt.Color(255, 255, 204));
        firstNameValidationLabel.setMinimumSize(new java.awt.Dimension(500, 500));
        firstNameValidationLabel.setPreferredSize(new java.awt.Dimension(100, 629));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("View Submitted Details");

        FirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FirstName.setText("First Name");

        LastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastName.setText("Last Name");

        Age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Age.setText("Age");

        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setText("Email");

        Message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message.setText("Message");

        UploadPhoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UploadPhoto.setText("Uploaded Photo");

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        messageText.setColumns(20);
        messageText.setLineWrap(true);
        messageText.setRows(5);
        messageText.setCaretColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(messageText);

        maleSelect.setText("Male");
        maleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSelectActionPerformed(evt);
            }
        });

        femaleSelect.setText("Female");
        femaleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleSelectActionPerformed(evt);
            }
        });

        otherSelect.setText("Other");
        otherSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSelectActionPerformed(evt);
            }
        });

        Message1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message1.setText("Gender");

        ageText.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        ageText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTextKeyPressed(evt);
            }
        });

        howDidYouKnowAboutUs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        howDidYouKnowAboutUs.setText("Patient Type");

        typeSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one...", "Acute", "Chronic", "Pediatric" }));

        previewImage.setBackground(new java.awt.Color(255, 255, 204));
        previewImage.setMaximumSize(new java.awt.Dimension(150, 150));
        previewImage.setMinimumSize(new java.awt.Dimension(150, 150));
        previewImage.setOpaque(true);
        previewImage.setPreferredSize(new java.awt.Dimension(150, 150));

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setText("Date of Birth");

        javax.swing.GroupLayout firstNameValidationLabelLayout = new javax.swing.GroupLayout(firstNameValidationLabel);
        firstNameValidationLabel.setLayout(firstNameValidationLabelLayout);
        firstNameValidationLabelLayout.setHorizontalGroup(
            firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstName)
                                    .addComponent(Age)
                                    .addComponent(Email)
                                    .addComponent(Message1))
                                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(LastName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(femaleSelect)
                                                .addGap(35, 35, 35)
                                                .addComponent(maleSelect)
                                                .addGap(40, 40, 40)
                                                .addComponent(otherSelect))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstNameValidationLabelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(114, 114, 114))))
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addComponent(howDidYouKnowAboutUs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addComponent(UploadPhoto)
                                .addGap(18, 18, 18)
                                .addComponent(previewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Message)
                                    .addComponent(date))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(234, 234, 234)))))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstNameValidationLabelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(83, 83, 83))
        );
        firstNameValidationLabelLayout.setVerticalGroup(
            firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstName)
                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LastName)
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age)
                    .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Message1)
                    .addComponent(femaleSelect)
                    .addComponent(maleSelect)
                    .addComponent(otherSelect))
                .addGap(18, 18, 18)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howDidYouKnowAboutUs)
                    .addComponent(typeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Message)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UploadPhoto)
                    .addComponent(previewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(firstNameValidationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(firstNameValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void maleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleSelectActionPerformed

    private void femaleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleSelectActionPerformed

    private void otherSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherSelectActionPerformed

    private void ageTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ageTextKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Message1;
    private javax.swing.JLabel UploadPhoto;
    private javax.swing.JSpinner ageText;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser dateText;
    private javax.swing.JTextField emailText;
    private javax.swing.JRadioButton femaleSelect;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JPanel firstNameValidationLabel;
    private javax.swing.JLabel howDidYouKnowAboutUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JRadioButton maleSelect;
    private javax.swing.JTextArea messageText;
    private javax.swing.JRadioButton otherSelect;
    private javax.swing.JLabel previewImage;
    private javax.swing.JComboBox<String> typeSelect;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        firstNameText.setText(newUser.getFirstName());
        lastNameText.setText(newUser.getLastName());
        int age = newUser.getAge();
        ageText.setValue(age);
        emailText.setText(newUser.getEmail());

        String gender = newUser.getGender();
        if (gender != null) {
            switch (gender) {
                case "Male" -> maleSelect.setSelected(true);
                case "Female" -> femaleSelect.setSelected(true);
                case "Other" -> otherSelect.setSelected(true);
            }
        }

        String type = newUser.getType();
        if (type != null) {
            typeSelect.setSelectedItem(type);
        }
        dateText.setDate(newUser.getDate());
        messageText.setText(newUser.getMessage());
        
        String imagePath = newUser.getImagePath();
    System.out.println(imagePath);
    if (imagePath != null) {
        ImageIcon imageIcon = new ImageIcon(imagePath);

        int labelWidth = 81;
        int labelHeight = 89;
        previewImage.setPreferredSize(new Dimension(labelWidth, labelHeight));

        if (labelWidth > 0 && labelHeight > 0) {
            
            Image image = imageIcon.getImage();
            Image scaledImage = image.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(scaledImage);
        }
        previewImage.setIcon(imageIcon);
    }
    }
}
    

