/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.lab4_javaswing;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.*;
import java.io.File;
import java.util.Date;
import java.util.Calendar;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Image;
/**
 *
 * @author Admin
 */
public class formPanel extends javax.swing.JPanel {

    
    final JPanel bottomPanel;
    private User newUser = new User();
    
    public formPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }
    private int i;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderOptions = new javax.swing.ButtonGroup();
        firstNameValidationLabel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        UploadPhoto = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageText = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        uploadFile = new javax.swing.JButton();
        maleSelect = new javax.swing.JRadioButton();
        femaleSelect = new javax.swing.JRadioButton();
        otherSelect = new javax.swing.JRadioButton();
        Message1 = new javax.swing.JLabel();
        ageText = new javax.swing.JSpinner();
        howDidYouKnowAboutUs = new javax.swing.JLabel();
        typeSelect = new javax.swing.JComboBox<>();
        previewImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateText = new com.toedter.calendar.JDateChooser();
        date = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(200, 500));

        firstNameValidationLabel.setBackground(new java.awt.Color(255, 255, 204));
        firstNameValidationLabel.setMinimumSize(new java.awt.Dimension(500, 500));
        firstNameValidationLabel.setPreferredSize(new java.awt.Dimension(100, 629));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Patient Registration Form");

        FirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FirstName.setText("First Name");

        LastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LastName.setText("Last Name");

        Age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Age.setText("Age");

        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setText("Email");

        Message.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message.setText("Message");

        UploadPhoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UploadPhoto.setText("Upload Photo");

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        messageText.setColumns(20);
        messageText.setLineWrap(true);
        messageText.setRows(5);
        messageText.setCaretColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(messageText);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));

        uploadFile.setBackground(new java.awt.Color(0, 204, 204));
        uploadFile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uploadFile.setForeground(new java.awt.Color(255, 255, 255));
        uploadFile.setText("Choose a file...");
        uploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadFileActionPerformed(evt);
            }
        });

        genderOptions.add(maleSelect);
        maleSelect.setText("Male");
        maleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleSelectActionPerformed(evt);
            }
        });

        genderOptions.add(femaleSelect);
        femaleSelect.setText("Female");
        femaleSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleSelectActionPerformed(evt);
            }
        });

        genderOptions.add(otherSelect);
        otherSelect.setText("Other");
        otherSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherSelectActionPerformed(evt);
            }
        });

        Message1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Message1.setText("Gender");

        ageText.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        ageText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTextKeyPressed(evt);
            }
        });

        howDidYouKnowAboutUs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        howDidYouKnowAboutUs.setText("Patient Type");

        typeSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one...", "Acute", "Chronic", "Pediatric" }));

        previewImage.setBackground(new java.awt.Color(255, 255, 204));
        previewImage.setMaximumSize(new java.awt.Dimension(150, 150));
        previewImage.setMinimumSize(new java.awt.Dimension(150, 150));
        previewImage.setOpaque(true);
        previewImage.setPreferredSize(new java.awt.Dimension(150, 150));

        date.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date.setText("Date of Birth");

        javax.swing.GroupLayout firstNameValidationLabelLayout = new javax.swing.GroupLayout(firstNameValidationLabel);
        firstNameValidationLabel.setLayout(firstNameValidationLabelLayout);
        firstNameValidationLabelLayout.setHorizontalGroup(
            firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(234, 234, 234)))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(howDidYouKnowAboutUs)
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstName)
                                    .addComponent(Age)
                                    .addComponent(Email)
                                    .addComponent(Message1))
                                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LastName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                                .addComponent(femaleSelect)
                                                .addGap(38, 38, 38)
                                                .addComponent(maleSelect)
                                                .addGap(33, 33, 33)
                                                .addComponent(otherSelect))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(typeSelect, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dateText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))))))
                            .addComponent(Message)
                            .addComponent(date)
                            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                                .addComponent(UploadPhoto)
                                .addGap(18, 18, 18)
                                .addComponent(uploadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        firstNameValidationLabelLayout.setVerticalGroup(
            firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FirstName)
                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LastName)
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstNameValidationLabelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Age))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Message1)
                    .addComponent(femaleSelect)
                    .addComponent(maleSelect)
                    .addComponent(otherSelect))
                .addGap(18, 18, 18)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(howDidYouKnowAboutUs)
                    .addComponent(typeSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Message)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstNameValidationLabelLayout.createSequentialGroup()
                        .addGroup(firstNameValidationLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UploadPhoto)
                            .addComponent(uploadFile))
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(previewImage, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(firstNameValidationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(firstNameValidationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed
    
    private void validateAllField(){
        boolean hasError = false;

    String firstName = firstNameText.getText();
    String lastName = lastNameText.getText();
    int age = (int) ageText.getValue();
    String email = emailText.getText();
    String selectedType = typeSelect.getSelectedItem().toString();
    String message = messageText.getText();
    String gender = "";

    
    if (firstName.isEmpty() || firstName.length() > 26 || !firstName.matches("^[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(null, "Please enter a First Name with: \n1. Length between 1 and 20 characters. \n2. Chararcters from A...Z or a..z.\n3. No special characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    
    if (lastName.isEmpty() || lastName.length() > 26 || !lastName.matches("^[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(null, "Please enter a Last Name with: \n1. Length between 1 and 20 characters. \n2. Chararcters from A...Z or a..z.\n3. No special characters.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    
    if (age < 12 || age > 100) {
        JOptionPane.showMessageDialog(null, "Please enter age between 12 and 100 (both inclusive).", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    
    if (!email.matches("[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        JOptionPane.showMessageDialog(null, "Please enetr valid email address.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    
    if (maleSelect.isSelected()) {
        gender = "Male";
    } else if (femaleSelect.isSelected()) {
        gender = "Female";
    } else if (otherSelect.isSelected()) {
        gender = "Other";
    } else {
        JOptionPane.showMessageDialog(null, "Please select a gender!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    
    if ("Select one...".equals(selectedType)) {
        JOptionPane.showMessageDialog(null, "Please select a patient type!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    
    //if (date == null) {
      //  JOptionPane.showMessageDialog(this, "Please select a valid date.", "Date Error", JOptionPane.ERROR_MESSAGE);
    //}
    Calendar selectedCalendar = Calendar.getInstance();
    Date selectedDate = dateText.getDate();
    selectedCalendar.setTime(selectedDate);
    Calendar todayDate = Calendar.getInstance();
    int minAge = 12;
    int maxAge = 100;
    Calendar minBirthDate = (Calendar) todayDate.clone();
    minBirthDate.add(Calendar.YEAR, -maxAge);
    Calendar maxBirthDate = (Calendar) todayDate.clone();
    maxBirthDate.add(Calendar.YEAR, -minAge);
    if (selectedCalendar.after(maxBirthDate) || selectedCalendar.before(minBirthDate)) {
        JOptionPane.showMessageDialog(null, "Please enter valid date!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    
    if (message.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a message!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        hasError = true;
    }

    if (!hasError && i==2) {
       
        newUser.setFirstName(firstName);
        newUser.setLastName(lastName);
        newUser.setAge(age);
        newUser.setEmail(email);
        newUser.setGender(gender);
        newUser.setType(selectedType);
        newUser.setMessage(message);
        newUser.setDate(selectedDate);
        
        detailsPanel newDetailsPanel = new detailsPanel(newUser);
        bottomPanel.add(newDetailsPanel, "details");
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.show(bottomPanel, "details");
        
        
    }
        
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        validateAllField();
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadFileActionPerformed
        // TODO add your handling code here:
        
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png"));
                int returnValue = fileChooser.showOpenDialog(null);

                if (returnValue == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    if (selectedFile.getName().endsWith(".jpg") || selectedFile.getName().endsWith(".jpeg") || selectedFile.getName().endsWith(".png")) {
                        newUser.setImagePath(selectedFile.getAbsolutePath());
                        ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());

                        int labelWidth = previewImage.getWidth();
                        int labelHeight = previewImage.getHeight();

                        Image image = imageIcon.getImage();
                        Image scaledImage = image.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
                        imageIcon = new ImageIcon(scaledImage);
                        //ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
                        previewImage.setIcon(imageIcon);
                        i=2;
                        
                    } else {
                        JOptionPane.showMessageDialog(null, "Please select an image!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    }
                }

    }//GEN-LAST:event_uploadFileActionPerformed

    private void maleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleSelectActionPerformed

    private void femaleSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleSelectActionPerformed

    private void otherSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherSelectActionPerformed

    private void ageTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ageTextKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Message1;
    private javax.swing.JLabel UploadPhoto;
    private javax.swing.JSpinner ageText;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser dateText;
    private javax.swing.JTextField emailText;
    private javax.swing.JRadioButton femaleSelect;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JPanel firstNameValidationLabel;
    private javax.swing.ButtonGroup genderOptions;
    private javax.swing.JLabel howDidYouKnowAboutUs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JRadioButton maleSelect;
    private javax.swing.JTextArea messageText;
    private javax.swing.JRadioButton otherSelect;
    private javax.swing.JLabel previewImage;
    private javax.swing.JComboBox<String> typeSelect;
    private javax.swing.JButton uploadFile;
    // End of variables declaration//GEN-END:variables
}
